---
- name: create nginx symlink
  become: yes
  file:
    src: '/etc/nginx/sites-available/{{ nginx.server_name }}'
    dest: '/etc/nginx/sites-enabled/{{ nginx.server_name }}'
    state: link

- name: restart nginx
  become: yes
  service:
    name: nginx
    state: restarted
  