---
- name: Ensure nginx is installed
  become: true
  apt:
    name: nginx

- name: Update nginx config file
  become: yes
  template:
    src: templates/app_flask_nginx_conf.j2
    dest: '/etc/nginx/sites-available/{{ nginx.config_name }}'
  notify:
    - create nginx symlink
    - restart nginx

- name: remove the default nginx conf
  become: yes
  file:
    state: absent
    path: '/etc/nginx/sites-enabled/default'
  