---
ansible_ssh_pipelining: true

git_clone: false

app_user:
  username: "ubuntu"

app_title: "flaskapp"

app_name: "flaskapp"
app_directory: "/home/{{ app_user.username }}/apps/{{ app_name }}"
log_directory: '/var/log/{{ app_name }}'

api_src_directory: "{{ app_directory }}/flaskapp"
api_venv_directory: "{{ app_directory }}/flaskapp/env"

api_domain_name: "flaskapp.example.com"
nginx:
  config_name: flaskapp
  server_name: flaskapp

postgres:
  username: "{{app_title}}user"
  password: "{{app_title}}password"
  dbname: "{{app_title}}db"
  host: "localhost"
  port: "5432"
